language: swift
xcode_project: whereclosest.xcodeproj 
xcode_scheme: whereclosest
osx_image: xcode9.4
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
script:
  - xcodebuild -project whereclosest.xcodeproj -scheme whereclosest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO 
